#!/bin/sh
set -eu

# URL base del API (puede ser vacía para usar rutas relativas con proxy Nginx)
API_BASE_URL="${API_BASE_URL:-}"
API_BASE_URL="${API_BASE_URL%/}"
export API_BASE_URL

# Variables de Firebase (necesarias para autenticación y push notifications)
FIREBASE_WEB_API_KEY="${FIREBASE_WEB_API_KEY:-}"
FIREBASE_WEB_AUTH_DOMAIN="${FIREBASE_WEB_AUTH_DOMAIN:-}"
FIREBASE_WEB_PROJECT_ID="${FIREBASE_WEB_PROJECT_ID:-}"
FIREBASE_WEB_STORAGE_BUCKET="${FIREBASE_WEB_STORAGE_BUCKET:-}"
FIREBASE_WEB_MESSAGING_SENDER_ID="${FIREBASE_WEB_MESSAGING_SENDER_ID:-}"
FIREBASE_WEB_APP_ID="${FIREBASE_WEB_APP_ID:-}"
FIREBASE_WEB_MEASUREMENT_ID="${FIREBASE_WEB_MEASUREMENT_ID:-}"
FIREBASE_WEB_VAPID_KEY="${FIREBASE_WEB_VAPID_KEY:-}"

export FIREBASE_WEB_API_KEY FIREBASE_WEB_AUTH_DOMAIN FIREBASE_WEB_PROJECT_ID
export FIREBASE_WEB_STORAGE_BUCKET FIREBASE_WEB_MESSAGING_SENDER_ID
export FIREBASE_WEB_APP_ID FIREBASE_WEB_MEASUREMENT_ID FIREBASE_WEB_VAPID_KEY

envsubst '${API_BASE_URL} ${FIREBASE_WEB_API_KEY} ${FIREBASE_WEB_AUTH_DOMAIN} ${FIREBASE_WEB_PROJECT_ID} ${FIREBASE_WEB_STORAGE_BUCKET} ${FIREBASE_WEB_MESSAGING_SENDER_ID} ${FIREBASE_WEB_APP_ID} ${FIREBASE_WEB_MEASUREMENT_ID} ${FIREBASE_WEB_VAPID_KEY}' \
  < /usr/share/nginx/html/runtime-config.js.template \
  > /usr/share/nginx/html/runtime-config.js
