import { ApplicationConfig, importProvidersFrom, isDevMode } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideServiceWorker } from '@angular/service-worker';
import { routes } from './app.routes';
import { adminUserHeaderInterceptor } from './core/interceptors/admin-user-header.interceptor';
import { adminAuthErrorInterceptor } from './core/interceptors/admin-auth-error.interceptor';
import { funcionarioUserHeaderInterceptor } from './core/interceptors/funcionario-user-header.interceptor';
import { funcionarioAuthErrorInterceptor } from './core/interceptors/funcionario-auth-error.interceptor';
import { offlineHttpInterceptor } from './core/offline/offline-http.interceptor';
import {
  LucideAngularModule,
  Settings2,
  Plus,
  Search,
  Bot,
  ClipboardList,
  RefreshCw,
  CheckCircle2,
  CheckCircle,
  Pencil,
  PauseCircle,
  CircleDot,
  Link,
  X,
  Send,
  Rocket,
  Sparkles,
  Play,
  Square,
  Diamond,
  Split,
  Merge,
  StopCircle,
  Lightbulb,
  Folder,
  FileText,
  Shuffle,
  Check,
  Save,
  Trash2,
  ZoomIn,
  ZoomOut,
  Focus,
  PlayCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowLeftRight,
  Users,
  Wifi,
  WifiOff,
  AlertTriangle,
  AlertCircle,
  Activity,
  ChartColumn,
  CloudCheck,
  Gauge,
  Lock,
  Mic,
  MicOff,
  User,
  UserCheck,
  Ban,
  Zap,
  Info,
  Volume2,
  VolumeX,
  Loader2,
  BrainCircuit,
  Route,
  Timer,
  ListOrdered,
  ChevronUp,
  ChevronDown,
  LayoutTemplate,
  Layers,
  GripVertical,
  Inbox,
  Type,
  Hash,
  Calendar,
  ToggleLeft,
  CircleChevronDown,
  SquareCheckBig,
  Grid2x2,
  Tag,
  Paperclip,
  FilePen,
  Settings,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(
      withInterceptors([
        // Headers van primero para que el interceptor offline los vea ya incluidos
        adminUserHeaderInterceptor,
        funcionarioUserHeaderInterceptor,
        adminAuthErrorInterceptor,
        funcionarioAuthErrorInterceptor,
        // Offline va último: intercepta errores de red y encola mutaciones
        offlineHttpInterceptor,
      ])
    ),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        Settings2,
        Plus,
        Search,
        Bot,
        ClipboardList,
        RefreshCw,
        CheckCircle2,
        CheckCircle,
        Pencil,
        PauseCircle,
        CircleDot,
        Link,
        X,
        Send,
        Rocket,
        Sparkles,
        Play,
        Square,
        Diamond,
        Split,
        Merge,
        StopCircle,
        Lightbulb,
        Folder,
        FileText,
        Shuffle,
        Check,
        Save,
        Trash2,
        ZoomIn,
        ZoomOut,
        Focus,
        PlayCircle,
        ArrowLeft,
        ArrowRight,
        ArrowUpDown,
        ArrowLeftRight,
        Users,
        User,
        Wifi,
        WifiOff,
        AlertTriangle,
        AlertCircle,
        Activity,
        ChartColumn,
        CloudCheck,
        Gauge,
        Lock,
        Mic,
        MicOff,
        UserCheck,
        Ban,
        Zap,
        Info,
        Volume2,
        VolumeX,
        Loader2,
        BrainCircuit,
        Route,
        Timer,
        ListOrdered,
        ChevronUp,
        ChevronDown,
        LayoutTemplate,
        Layers,
        GripVertical,
        Inbox,
        Type,
        Hash,
        Calendar,
        ToggleLeft,
        CircleChevronDown,
        SquareCheckBig,
        Grid2x2,
        Tag,
        Paperclip,
        FilePen,
        Settings,
      })
    )
  ]
};
